version: "3"
services:
  db:
    restart: always
    container_name: tts-db
    image: postgres:9.6
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    container_name: tts-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/site-enabled:/etc/nginx/conf.d
    depends_on:
      - web

  redis:
    restart: always
    container_name: tts-redis
    image: redis:3.0
    expose:
      - "6379"

  web:
    # replace username/repo:tag with your name and image details
    build: .
    image: tts-image
    container_name: tts-app
    environment:
      - DEBUG=False
      - STATICFILES_STORAGE=whitenoise.storage.CompressedManifestStaticFilesStorage
      - DATABASE=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - CELERY_SERVER=redis
    depends_on:
      - db
    expose:
      - "8888"
    entrypoint: ./entry_point.sh
    command: gunicorn urdu_tts.wsgi:application -w 2 -b :8888 --timeout 120 --graceful-timeout 120 --worker-class gevent
    restart: always
    volumes:
      - media:/home/docker/code/media

  celery:
    image: tts-image
    container_name: tts-celery
    command: celery -A urdu_tts worker --loglevel=info
    depends_on:
      - web
    links:
      - db
      - redis
    environment:
      - DEBUG=False
      - STATICFILES_STORAGE=whitenoise.storage.CompressedManifestStaticFilesStorage
      - DATABASE=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - CELERY_SERVER=redis
    volumes:
      - data-volume:/home/docker/code/media

  volumes:
     data-volume: