version: "3"

volumes:
    static:
    media:

services:
  db:
    restart: always
    container_name: tts-db
    image: postgres:9.6
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:latest
    container_name: tts-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/site-enabled:/etc/nginx/conf.d
      - static:/home/docker/code/staticfiles
      - media:/home/docker/code/media
    depends_on:
      - web

  web:
    # replace username/repo:tag with your name and image details
    build: .
    image: tts-image
    container_name: tts-app
    environment:
      - DEBUG=False
      - STATICFILES_STORAGE=whitenoise.storage.CompressedManifestStaticFilesStorage
      - DATABASE=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
    expose:
      - "8888"
    entrypoint: ./entry_point.sh
    command: gunicorn urdu_tts.wsgi:application -w 2 -b :8888 --timeout 120 --graceful-timeout 120 --worker-class gevent
    restart: always
    volumes:
      - ./urdu_tts:/home/docker/code/
      - static:/home/docker/code/staticfiles
      - media:/home/docker/code/media