version: "3"
services:
  db:
    restart: always
    container_name: tts-db
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tts
    expose:
      - "5432"

  nginx:
    image: nginx:latest
    container_name: tts-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/site-enabled:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    # replace username/repo:tag with your name and image details
    build: .
    container_name: tts-app
    environment:
      - DATABASE=db
      - DEBUG=False
    depends_on:
      - db
    expose:
      - "8888"
    entrypoint: ./entry_point.sh
    command: gunicorn urdu_tts.wsgi:application -w 2 -b :8888 --timeout 120 --graceful-timeout 120 --worker-class gevent
    restart: always