# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrecord',
            name='age',
            field=models.CharField(choices=[('1-15', '<15'), ('15-25', '15-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('45+', '45+')], default='15-25', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationrecord',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
    ]
