# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_auto_20171021_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvoice',
            name='voice',
            field=models.CharField(default='', max_length=200),
        ),
    ]
