# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-13 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0002_auto_20180213_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationrecord',
            old_name='understandability',
            new_name='intelligibility',
        ),
    ]
